CREATE OR REPLACE PACKAGE PatientUtils AS
  PROCEDURE UpdatePatientInfo(
    P_DATE_OF_BIRTH IN OUT VARCHAR2,
    P_CONTACT_NUMBER IN OUT VARCHAR2,
    P_LASTNAME IN OUT VARCHAR2
  );
END PatientUtils;
/

CREATE OR REPLACE PACKAGE BODY PatientUtils AS
  PROCEDURE UpdatePatientInfo(
    P_DATE_OF_BIRTH IN OUT VARCHAR2,
    P_CONTACT_NUMBER IN OUT VARCHAR2,
    P_LASTNAME IN OUT VARCHAR2
  ) IS
  BEGIN
    IF P_DATE_OF_BIRTH IS NOT NULL THEN
      P_DATE_OF_BIRTH := TO_CHAR(TO_DATE(P_DATE_OF_BIRTH, 'DD-MM-YYYY'), 'DD/MM/YYYY');
    END IF;

    IF P_CONTACT_NUMBER IS NOT NULL THEN
      P_CONTACT_NUMBER := REGEXP_REPLACE(P_CONTACT_NUMBER, '(\d{3})(\d{3})(\d{4})', '\1-\2-\3');
    END IF;

    IF LENGTH(P_LASTNAME) < 3 THEN
      P_LASTNAME := P_LASTNAME || '?';
    END IF;
  END UpdatePatientInfo;
END PatientUtils;
/

CREATE OR REPLACE TRIGGER before_insert_update_patient
BEFORE INSERT OR UPDATE ON PATIENT
FOR EACH ROW
BEGIN
  PatientUtils.UpdatePatientInfo(
    :NEW.DATE_OF_BIRTH,
    :NEW.CONTACT_NUMBER,
    :NEW.LASTNAME
  );
END before_insert_update_patient;
/